logging:
  path: ./logs

spring:
  datasource:
    mysql:
      url: jdbc:mysql://mms-mysql-test.idc.yst.com.cn:3306/dealer?autoReconnect=true&amp;autoReconnectForPools=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
      username: dealer
      password: dealertest
  redis:
    host: redis-test.idc.yst.com.cn
  http:
    multipart:
      max-file-size: 20Mb
      max-request-size: 100Mb

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-test.idc.yst.com.cn:8080/eureka/
dubbo:
  zookeeper:
    address: zookeeper-test.idc.yst.com.cn:2181
  protocol:
    port: 20889

attachment:
  path:  /home/admin/dealer/market/

nfsq:
  sso:
    url: http://firefox-mrk.test.yst.com.cn/NFSpring_auth_service/web/desktop/initDesktop

#server:
#  port: 9090
