logging:
  path: ./logs

spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/practice?autoReconnect=true&amp;computer?autoReconnect=true&amp;autoReconnectForPools=true&allowMultiQueries=true
      username: growlithe
      password: growlithe
